import { CITATIONS, type Citation } from "@gradpath/engine";

// About & Methodology. The methodology list is generated from the same
// CITATIONS the engine uses for its calculations, so this page can never drift
// from what the math actually cites — it is the single source of truth.

const PRINCIPLES: Array<{ title: string; body: string }> = [
  {
    title: "Every number cites an official source",
    body: "Payments and eligibility come from published rules (federal regulations, StudentAid.gov, HHS, IRS, CFPB). Each result links its source, and you can check our work.",
  },
  {
    title: "No AI in the math",
    body: "Calculations are deterministic and rule-based, not generated by a language model. A wrong number is a fixable bug with a test, not a guess.",
  },
  {
    title: "Your data never leaves your device",
    body: "Everything you enter — income, balances, uploaded aid files — is processed in your browser and saved only in this browser's local storage. Nothing is uploaded to a server or shared.",
  },
  {
    title: "Free, nonprofit, student-direct",
    body: "GradPath is free and open source, built for students and families — never sold to institutions, and no lead generation.",
  },
];

// Group the engine's citations into the three lifecycle stages for display.
const STAGE_GROUPS: Array<{ heading: string; ids: string[] }> = [
  {
    heading: "Afford — paying for college",
    ids: [CITATIONS.netPrice.id, CITATIONS.awardLetterCompare.id, CITATIONS.loanLimits.id, CITATIONS.plan529.id, CITATIONS.grandparent529.id, CITATIONS.privateVsFederal.id],
  },
  {
    heading: "Repay — repayment & forgiveness",
    ids: [CITATIONS.standardPlan.id, CITATIONS.ibr.id, CITATIONS.rap.id, CITATIONS.pslf.id, CITATIONS.hhsPoverty2025.id, CITATIONS.myAidData.id],
  },
];

const ALL: Citation[] = Object.values(CITATIONS);
const byId = (id: string) => ALL.find((c) => c.id === id);

export function AboutStage() {
  return (
    <div className="card">
      <h1>About GradPath &amp; how it works</h1>
      <p className="hint">
        GradPath is a free, nonprofit tool for the three stages of paying for
        college: applying, affording, and repaying. Here is what it does and
        exactly where every number comes from.
      </p>

      <section>
        <h2>Our principles</h2>
        <ul className="principles">
          {PRINCIPLES.map((p) => (
            <li key={p.title}>
              <strong>{p.title}.</strong> {p.body}
            </li>
          ))}
        </ul>
      </section>

      <section>
        <h2>Methodology — sources behind every number</h2>
        <p className="hint">
          These are the official sources the calculators are built on. If any
          rule ever diverges from its cited source, that is a bug — please
          report it.
        </p>
        {STAGE_GROUPS.map((group) => (
          <div key={group.heading}>
            <h3>{group.heading}</h3>
            <ul className="sources">
              {group.ids.map((id) => {
                const c = byId(id);
                if (!c) return null;
                return (
                  <li key={c.id}>
                    <a href={c.url} target="_blank" rel="noreferrer">
                      {c.title}
                    </a>
                    {c.note ? <span className="hint"> — {c.note}</span> : null}
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </section>

      <section>
        <h2>What this is not</h2>
        <p>
          GradPath screens and estimates; it does not certify anything. It is
          not financial, tax, or legal advice, and it is not affiliated with the
          U.S. Department of Education. Always confirm with StudentAid.gov, your
          loan servicer, or a financial aid professional before acting.
        </p>
      </section>

      <section>
        <h2>Open source</h2>
        <p>
          The code and every calculation rule are public and auditable at{" "}
          <a
            href="https://github.com/venkatchinta/grad-path"
            target="_blank"
            rel="noreferrer"
          >
            github.com/venkatchinta/grad-path
          </a>
          .
        </p>
      </section>
    </div>
  );
}
